default_platform(:ios)


platform :ios do
    lane :build_and_export do
        increment_build_number(build_number: "1.1")
        version = increment_version_number(version_number: "1.1")
        gym
        firebase_app_distribution(
            app: "1:422227624546:ios:008dc02a213c24634e473b",
            testers: "o.frankiv@ukma.edu.ua",
            release_notes: "Версія #{version}",
            ipa_path: "./output/output_archive.ipa",
            service_credentials_file: "./creditals.json",
            googleservice_info_plist_path: "./GoogleService-Info.plist"
        )
    end

    lane :take_screenshots do
        snapshot(
            output_directory: "./screenshots"
        )
    end
end
